# Default values for fpm-laravel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

app:
  key: base64:r3qmKktGeBi6Z/5Ax=

directory: /app
name: 'Vibspecdb'
persistence:
  enabled: true
  existingClaim: ""
  path: storage/app
  storage: 2Gi

image:
  app:
    image: docker.photonicdata.science/app_laravel_backend
    tag: v0.1.0
    name: fpm-server
    pullPolicy: Always
    postStart: "&& echo 'Hello from the postStart handler' > /usr/share/message"
  nginx:
    image: docker.photonicdata.science/app_nginx
    tag: v0.1.0
    name: nginx-server
    pullPolicy: Always

imagePullSecrets:
  - name: registrypullsecret

EnvConfigMapRef:
  name: "laravel-in-kubernetes"
  enabled: true
EnvSecretRef:
  enabled: true
  name: "laravel-in-kubernetes"
EnvSecretRefServices:
  enabled: true
  name: "laravel-in-kubernetes-services"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: vibspecdb.k8s.photonicdata.science
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

storage:
  pvc:
    enabled: true
    existingClaim: ""
    annotations: {}
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    storage: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: true

migrate:
  enabled: false
  timeout: 180
  cmd: "php artisan migrate --force"

postgresql:
  enabled: true
  image:
    tag: 14.3.0-debian-10-r17
  auth:
    username: "psguser"
    password: "secret"
    database: "laravelapp"
    postgresPassword: "adminSecret"
  port: "5432"
  host: "postgresql"
  global:
    storageClass: 'longhorn'
  persistence:
    enabled: false
    existingClaim: ""
    size: 1Gi
  resources:
    requests:
      memory: 100Mi
      cpu: 20m
    limits:
      memory: 150Mi
      cpu: 200m

worker:
  enabled: true
  replicaCount: 1
  autoscale:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    CPULimit: 70
    MemoryLimit: 1568Mi
  cmd: "php /app/artisan queue:work --sleep=3 --tries=3 --memory=128"
  resources:
    limits:
      cpu: 300m
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 100Mi

meilisearch:
  enabled: false
  image:
    repository: 'getmeili/meilisearch'
    tag: 'latest'
  host: 'meilisearch:7700'
  masterKey: 'meilikeymasterhere.1'
  searchKey: '123'
  publicKey: '123'
  scoutPrefix: 'dev_'
  scoutdriver: 'meilisearch'
  environment:
    MEILI_ENV: 'development'
  auth:
    existingMasterKeySecret: 'meili-master-key'
  persistence:
    enabled: false
    size: 5Gi
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

redis:
  enabled: true
  port: "6379"
  host: "redis-master"
  client: "predis"
  prefix: ''
  auth:
    password: 'redispasshere'
  global:
    storageClass: 'longhorn'
  replica:
    replicaCount: 1
  persistence:
    enabled: false
    size: 1Gi
  resources:
    requests:
      memory: 30Mi
      cpu: 10m
    limits:
      memory: 30Mi
      cpu: 50m

minio:
  enabled: false
  accessKey: 'MINIO_ROOT_USER'
  secretAccessKey: 'MINIO_ROOT_PASSWORD'
  bucket: 'local'
  endpoint: 'MINIO_ENDPOINT_URL'
  baseUrl: 'MINIO_ENDPOINT_URL'

gitlab:
  enabled: false
  accessKey: 'GITLAB_KEY'
  secretAccessKey: 'GITLAB_SECRET'
  redirectUrl: https://pageurl/auth/login/gitlab/callback
  baseUrl: https://private.gitlab.repo/

keycloak:
  enabled: false
  clientId: 'KEYCLOAK_CLIENT_ID'
  clientSecret: 'KEYCLOAK_CLIENT_SECRET'
  redirectUrl: 'https://pageurl/auth/login/keycloak/callback'
  baseUrl: 'https://pageurl/auth/'
  realm: 'RealmName'

smtp:
  enabled: false
  host: 'smtp.mailgun.org'
  port: 587
  from: 'from@company.de'
  user: 'postmaster@dev.com'
  password: "secret"
