apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.EnvConfigMapRef.name }}
data:
#App Properties
  APP_NAME: {{ .Values.appProperties.name }}
  APP_ENV: {{ .Values.appProperties.env }}
  APP_DEBUG: "{{ .Values.appProperties.debug }}"
  APP_URL: {{ .Values.appProperties.url }}
  APP_DESCRIPTION: {{ .Values.appProperties.description | indent 4 }}
  QUEUE_CONNECTION: {{ .Values.appProperties.queueConnection }}
  
#Log Properties
  LOG_CHANNEL: {{ .Values.logProperties.logChannel }}
  LOG_LEVEL: {{ .Values.logProperties.logLevel }}

#DB Properties
  DB_USERNAME: {{ required "A valid .Values.rdkitcatridgepostgres.auth.user entry required!" .Values.rdkitcatridgepostgres.auth.user }}
  DB_CONNECTION: {{ required "A valid .Values.rdkitcatridgepostgres.connection entry required!" .Values.rdkitcatridgepostgres.connection }}
  DB_HOST: {{ printf "%s-rdkitcatridgepostgres" .Release.Name | quote }}
  DB_PORT: {{ .Values.rdkitcatridgepostgres.port | default 5432 | quote }}
  DB_DATABASE: {{ required "A valid .Values.rdkitcatridgepostgres.auth.db entry required!" .Values.rdkitcatridgepostgres.auth.db }}

#File Storage Properties
  {{ if .Values.fileStorage.enabled }}
  FILESYSTEM_DRIVER: {{ .Values.fileStorage.fileSystemDriver }}
  FILESYSTEM_DRIVER_PUBLIC: {{ .Values.fileStorage.fileSystemDriverPublic }}
  AWS_DEFAULT_REGION: {{ .Values.fileStorage.awsDefaultRegion }}
  AWS_BUCKET: {{ .Values.fileStorage.awsBucket }}
  AWS_ENDPOINT: {{ .Values.fileStorage.awsEndpoint }}
  AWS_URL: {{ .Values.fileStorage.awsURL }}
  {{ end }}
  
#Mail Properties
  {{ if .Values.mail.enabled }}
  MAIL_MAILER: {{ .Values.mail.mailer }}
  MAIL_HOST: {{ .Values.mail.host }}
  MAIL_PORT: "{{ .Values.mail.port }}"
  MAIL_USERNAME: {{ .Values.mail.user }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.from }}
  MAIL_FROM_NAME: {{ .Values.mail.fromName }}
  {{ end }}

#Redis Properties
  {{ if .Values.redis.enabled }}
  SESSION_DRIVER: "{{ .Values.redis.sessionDriver }}"
  CACHE_DRIVER: {{ .Values.redis.cacheDriver }}
  REDIS_CLIENT: {{ .Values.redis.redisClient }}
  SESSION_LIFETIME: "{{ .Values.redis.sessionLifetime }}"
  MEMCACHED_HOST: {{ .Values.redis.memcachedHost }}
  REDIS_HOST: {{ printf "%s-redis-master" .Release.Name  | quote }}
  REDIS_PORT: {{ .Values.redis.port | default 6379 | quote }}
  {{ end }}

#Web Services
  EUROPEMC_WS_API: {{ .Values.webservices.europemcApi }}
  ORCID_ID_SEARCH_API: {{ .Values.webservices.orcidIdSearchApi }}
  ORCID_ID_EMPLOYMENT_API: {{ .Values.webservices.orcidIdEmploymentApi }}
  ORCID_ID_PERSON_API: {{ .Values.webservices.orcidIdPersonApi }}
  CM_API: {{ .Values.webservices.cmApi  }}

#DOI Properties
  DOI_HOST: {{ .Values.doi.doiHost }}
  DOI_PROVIDER: {{ .Values.doi.doiProvider }}

