apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "coconut-app.labels" . | nindent 4 }}
type: Opaque
data:
  #App Secrets
  APP_KEY: {{ required "A valid .Values.appProperties.key entry required! generate it with php artisan key:generate" .Values.appProperties.key |b64enc | quote }}

  #Mail Secrets
  {{- if .Values.mail.enabled }}
  MAIL_PASSWORD: {{ .Values.mail.password |b64enc | quote }}
  {{- end -}}

  #DB Secrets
  {{- if .Values.rdkitcatridgepostgres.enabled }}
  DB_PASSWORD: {{ required "A valid .Values.rdkitcatridgepostgres.auth.pgPassword entry required!" .Values.rdkitcatridgepostgres.auth.pgPassword |b64enc | quote }}
  {{- end -}}

  #File Storage Secrets
  {{- if .Values.fileStorage.enabled}}
  AWS_ACCESS_KEY_ID: {{ .Values.fileStorage.awsAccessKeyID |b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.fileStorage.awsSecretAccessKey |b64enc | quote }}
  {{- end -}}

  #Redis Secrets
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ required "A valid .Values.redis.auth.password entry required!" .Values.redis.auth.password |b64enc | quote }}
  {{- end -}}

  #LaraBug Secrets
  {{- if .Values.larabug.enabled }}
  LB_KEY: {{ .Values.larabug.lbKey |b64enc | quote }}
  LB_PROJECT_KEY: {{ .Values.larabug.lbProjectKey |b64enc | quote }}
  {{- end -}}

  #OAuth Properties Secrets
  {{- if .Values.oauthProperties.github.enabled }}
  GITHUB_CLIENT_ID: {{ .Values.oauthProperties.github.clientID |b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.oauthProperties.github.clientSecret |b64enc | quote }}
  {{- end -}}
  {{- if .Values.oauthProperties.google.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.oauthProperties.google.clientID |b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oauthProperties.google.clientSecret |b64enc | quote }}
  {{- end -}}

  {{- if .Values.datacite.enabled }}
  #Datacite Secrets
  DATACITE_USERNAME: {{ .Values.datacite.username |b64enc | quote }}
  DATACITE_SECRET: {{ .Values.datacite.secret |b64enc | quote }}
  {{- end -}}