# Default values for nmrxiv-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Default app properties for laravel.
appProperties:
  name: nmrXiv
  key:  
  env: development
  debug: true
  url: https://<your-url>/

logProperties:
  logChannel: stack
  logLevel: debug

#Enable this properties for Single Sign-On follow the documentation for more info https://docs.nmrxiv.org/docs/developer-guides/configurations/oauth
oauthProperties:
  enabled: false
  twitterClientID: 
  twitterClientSecret: 
  twitterRedirectUrl: 
  githubClientID: 
  githubClientSecret: 
  githubRedirectUrl: 

appImage:
  name: php
  repository: eu.gcr.io/nmrxiv/app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nginxImage:
  name: nginx
  repository: eu.gcr.io/nmrxiv/nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

EnvConfigMapRef:
  name: "nmrxiv-config-map"
  enabled: true
EnvSecretRef:
  name: "nmrxiv-secrets"
  enabled: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {
  fsGroup: 82
}

securityContext: {
  runAsUser: 82,
  readOnlyRootFilesystem: true
}


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {
    # kubernetes.io/ingress.global-static-ip-name: nmrxiv-app-ip-address
    # kubernetes.io/ingress.class: "nginx"
  }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 50M

# Uncomment below properties and replace it with your own smtp values to activate the mail server.
mail:
  enabled: false
  # host: 'smtp.uni-jena.de'
  # port: 587
  # from: info.nmrxiv@uni-jena.de
  # fromName: "nmrXiv-dev"
  # user: user
  # password: secret
  # mailer: smtp

# DB properties
postgresql:
  image:
    tag: 11.14.0-debian-10-r17   # immutable tags are recommended
  enabled: true
  # global:
  #   storageClass: standard
  connection: pgsql
  persistence:
    enabled: false
    existingClaim: ''
    size: 1Gi
  # host: nmrxiv-postgresql
  # port: 5432
  postgresqlDatabase: nmrxiv
  postgresqlPassword: secret
  postgresqlUsername: user
  resources:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 100Mi
      
pythonmicroservice:
  image:
    name: python-microservice
    repository: europe-west3-docker.pkg.dev/nmrxiv/nmrxiv-dev/nmrxiv-python-microservice
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  service:
    type: ClusterIP
    port: 80

nmrium:
  image:
    name: nmrium
    repository: europe-west3-docker.pkg.dev/nmrxiv/nmrxiv-dev/nmrium
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  service:
    type: LoadBalancer
    port: 80

redis:
  auth:
    password: password
  enabled: false
  global:
    storageClass: standard
  #host: nmrxiv-redis-master
  replica:
    replicaCount: 1
  persistence:
    enabled: false
    size: 1Gi
  port: 6379
  resources:
    limits:
      cpu: 50m
      memory: 30Mi
    requests:
      cpu: 10m
      memory: 30Mi

rabbitmq: 
  enabled: false
  port: 5672
  #host: nmrxiv-rabbitmq
  auth: 
    username: 'rabbitmq_user'
    password: 'password'
    #erlangCookie: 'erlangCookieerlangCookie'
  global:
    storageClass: 'standard'
  metrics:
    enabled: false
  ingress:
    enabled: false
    path: '/'
    hostname: ''

meilisearch: 
  enabled: false
  #Replace the host name with yours.
  host: 'nmrxiv-meilisearch:7700'
  secretKey: secretkey

storage:
  pvc:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    existingClaim: ''
    storage: 2Gi
    # storageClassName: standard

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
