chart-dirs:
  - charts/
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - meilisearch=https://meilisearch.github.io/meilisearch-kubernetes
check-version-increment: true
debug: true
remote: origin
target-branch: main
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
