apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nmrxiv-nmrxiv-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20