apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.EnvConfigMapRef.name }}
data:
#App Properties
  APP_NAME: {{ .Values.appProperties.name }}
  APP_ENV: {{ .Values.appProperties.env }}
  APP_DEBUG: "{{ .Values.appProperties.debug }}"
  APP_URL: {{ .Values.appProperties.url }}
  QUEUE_CONNECTION: {{ .Values.appProperties.queueConnection }}
  GITHUB_LICENSE_URL: {{ .Values.appProperties.githubLicenseUrl }}
  GET_DETAILS_BY_DOI_API: {{ .Values.appProperties.getDetailsByDoiApi }}
  
#Log Properties
  LOG_CHANNEL: {{ .Values.logProperties.logChannel }}
  LOG_LEVEL: {{ .Values.logProperties.logLevel }}

#DB Properties
  DB_USERNAME: {{ required "A valid Values.postgresql.auth.username entry required!" .Values.postgresql.auth.username }}
  DB_CONNECTION: {{ required "A valid .Values.postgresql.connection entry required!" .Values.postgresql.connection }}
  DB_HOST: {{ printf "%s-postgresql" .Release.Name | quote }}
  DB_PORT: {{ .Values.postgresql.port | default 5432 | quote }}
  DB_DATABASE: {{ required "A valid Values.postgresql.auth.database entry required!" .Values.postgresql.auth.database }}
  
#File Storage Properties
  {{ if .Values.fileStorage.enabled }}
  FILESYSTEM_DRIVER: {{ .Values.fileStorage.fileSystemDriver }}
  AWS_DEFAULT_REGION: {{ .Values.fileStorage.awsDefaultRegion }}
  AWS_BUCKET: {{ .Values.fileStorage.awsBucket }}
  AWS_ENDPOINT: {{ .Values.fileStorage.awsEndpoint }}
  AWS_URL: {{ .Values.fileStorage.awsURL }}
  AWS_BUCKET_PUBLIC: {{ .Values.fileStorage.awsBucketPublic }}
  {{ end }}

#Nmrium Properties
  NMRIUM_URL: {{ required "A valid .Values.nmrium.nmriumURL entry required!" .Values.nmrium.nmriumURL }}

#Python Microservice Properties
  PYTHON_WS_URL: {{ printf "%s-pythonmicroservice" .Release.Name }}
  PYTHON_WS_PORT: {{ .Values.pythonmicroservice.service.port | default 80 | quote }}

#Redis Properties
  {{ if .Values.redis.enabled }}
  SESSION_DRIVER: "{{ .Values.redis.sessionDriver }}"
  CACHE_DRIVER: {{ .Values.redis.cacheDriver }}
  REDIS_CLIENT: {{ .Values.redis.redisClient }}
  SESSION_LIFETIME: "{{ .Values.redis.sessionLifetime }}"
  MEMCACHED_HOST: {{ .Values.redis.memcachedHost }}
  REDIS_HOST: {{ printf "%s-redis-master" .Release.Name  | quote }}
  REDIS_PORT: {{ .Values.redis.port | default 6379 | quote }}
  {{ end }}

#RabbitMQ Properties
  {{ if .Values.rabbitmq.enabled }}
  QUEUE_CONNECTION: {{ .Values.rabbitmq.queueConnection }}
  RABBITMQ_HOST: {{ printf "%s-rabbitmq" .Release.Name | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | default 5672 | quote }}
  RABBITMQ_USER: {{ required "A valid .Values.rabbitmq.auth.username entry required!" .Values.rabbitmq.auth.username }}
  RABBITMQ_QUEUE: jobs
  {{ end }}

#Meilisearch Properties
  {{ if .Values.meilisearch.enabled }}
  SCOUT_DRIVER: {{ .Values.meilisearch.scout }}
  SCOUT_PREFIX: {{ .Values.meilisearch.scoutPrefix }}
  MEILISEARCH_HOST: {{ required "A valid .Values.meilisearch.host entry required!" .Values.meilisearch.host }}
  {{ end }}

#Mail Properties
  {{ if .Values.mail.enabled }}
  MAIL_MAILER: {{ .Values.mail.mailer }}
  MAIL_HOST: {{ .Values.mail.host }}
  MAIL_PORT: "{{ .Values.mail.port }}"
  MAIL_USERNAME: {{ .Values.mail.user }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.from }}
  MAIL_FROM_NAME: {{ .Values.mail.fromName }}
  {{ end }}

#OAuth Properties
  {{ if .Values.oauthProperties.enabled }}
  TWITTER_REDIRECT_URL: {{ .Values.oauthProperties.twitterRedirectUrl }}
  GITHUB_REDIRECT_URL: {{ .Values.oauthProperties.githubRedirectUrl }}
  ORCID_REDIRECT_URL: {{ .Values.oauthProperties.orcidRedirectUrl }}
  ORCID_ENVIRONMENT: {{ .Values.oauthProperties.orcidEnvironment }}
  {{ end }}