apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmrxiv-app.fullname" . }}
  labels:
    {{- include "nmrxiv-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nmrxiv-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      # annotations:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      labels:
        {{- include "nmrxiv-app.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
      #serviceAccountName: {{ include "nmrxiv-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: database-migrations
          image: "{{ .Values.appImage.app }}:{{ .Values.appImage.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.EnvConfigMapRef.name }}
            - secretRef:
                name: {{ .Values.EnvSecretRef.name }}
          command:
            - "php"
          args:
            - "artisan"
            - "migrate"
            - "--force"
      containers:
        - name: {{ .Values.nginxImage.name }}
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          image: "{{ .Values.nginxImage.app }}:{{ .Values.nginxImage.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 80

        - name: {{ .Values.appImage.name }}
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          image: "{{ .Values.appImage.app }}:{{ .Values.appImage.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.EnvConfigMapRef.name }}
            - secretRef:
                name: {{ .Values.EnvSecretRef.name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: testing
              mountPath: /var/www/html/storage/framework/testing
          resources: {}
          ports:
            - containerPort: 9000        


