{{- if .Values.meilisearch.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-master-key
type: Opaque
data:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey |b64enc | quote }}
{{- end }}