apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmrxiv-scheduler
spec:
  selector:
    matchLabels:
      app: nmrxiv-scheduler
  template:
    metadata:
      labels:
        app: nmrxiv-scheduler
    spec:
      containers:
      - name: nmrxiv-scheduler
        image: europe-west3-docker.pkg.dev/nmrxiv/nmrxiv-dev/nmrxiv-app:latest
        imagePullPolicy: Always
        command:
          - php
        args:
          - artisan
          - schedule:work          
        resources: {}
        volumeMounts:
          - name: logs
            mountPath: /var/www/html/storage/logs
          - name: cache
            mountPath: /var/www/html/storage/framework/cache
          - name: sessions
            mountPath: /var/www/html/storage/framework/sessions
          - name: views
            mountPath: /var/www/html/storage/framework/views
          - name: testing
            mountPath: /var/www/html/storage/framework/testing
        envFrom:
          - configMapRef:
              name: nmrxiv-config-map
          - secretRef:
              name: nmrxiv-secrets
      volumes:
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}