apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "nmrxiv-app.labels" . | nindent 4 }}
type: Opaque
data:
  #App Secrets
  APP_KEY: {{ required "A valid .Values.appProperties.key entry required! generate it with php artisan key:generate" .Values.appProperties.key |b64enc | quote }}

  #Mail Secrets
  {{- if .Values.mail.enabled }}
  MAIL_PASSWORD: {{ .Values.mail.password |b64enc | quote }}
  {{- end -}}

  #DB Secrets
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ required "A valid .Values.postgresql.auth.password entry required!" .Values.postgresql.auth.password |b64enc | quote }}
  {{- else if .Values.mysql.enabled }}
  DB_PASSWORD: {{ required "A valid .Values.postgresql.auth.password entry required!" .Values.postgresql.auth.password |b64enc | quote }}
  {{- end -}}

  #File Storage Secrets
  {{- if .Values.fileStorage.enabled}}
  AWS_ACCESS_KEY_ID: {{ .Values.fileStorage.awsAccessKeyID |b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.fileStorage.awsSecretAccessKey |b64enc | quote }}
  {{- end -}}

  #Redis Secrets
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ required "A valid .Values.redis.auth.password entry required!" .Values.redis.auth.password |b64enc | quote }}
  {{- end -}}

  #RabbitMQ Secrets
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: {{ required "A valid .Values.rabbitmq.auth.password entry required!" .Values.rabbitmq.auth.password |b64enc | quote }}
  {{- end -}}

  #Meilisearch Secrets
  {{- if .Values.meilisearch.enabled }}
  MEILISEARCH_KEY: {{ required "A valid .Values.meilisearch.searchKey entry required!" .Values.meilisearch.searchKey |b64enc | quote }}
  MEILISEARCH_PUBLICKEY: {{ required "A valid .Values.meilisearch.publicKey entry required!" .Values.meilisearch.publicKey |b64enc | quote }}
  {{- end -}}

  ##OAuth Properties Secrets
  {{- if .Values.oauthProperties.enabled }}
  TWITTER_CLIENT_ID: {{ .Values.oauthProperties.twitterClientID |b64enc | quote }}
  TWITTER_CLIENT_SECRET: {{ .Values.oauthProperties.twitterClientSecret |b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.oauthProperties.githubClientID |b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.oauthProperties.githubClientSecret |b64enc | quote }}
  ORCID_CLIENT_ID: {{ .Values.oauthProperties.orcidClientID |b64enc | quote }}
  ORCID_CLIENT_SECRET: {{ .Values.oauthProperties.orcidClientSecret |b64enc | quote }}
  {{- end -}}

#LaraBug Secrets
  {{- if .Values.larabug.enabled }}
  LB_KEY: {{ .Values.larabug.lbKey }}
  LB_PROJECT_KEY: {{ .Values.larabug.lbProjectKey }}
  {{- end -}}
