apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "nmrxiv-nodejs-microservice.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.app.key |b64enc | quote }}