apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "vibspecdb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.smtp.enabled }}
  MAIL_PASSWORD: {{ required "A valid .Values.smtp.password entry required!" .Values.smtp.password |b64enc | quote }}
  {{- end -}}
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ required "A valid .Values.postgresql.auth.password entry required!" .Values.postgresql.auth.password |b64enc | quote }}
  {{- end -}}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ required "A valid .Values.redis.auth.password entry required!" .Values.redis.auth.password |b64enc | quote }}
  {{- end -}}