apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EnvSecretRef.name }}
  labels:
    {{- include "nmrkit.labels" . | nindent 4 }}
type: Opaque
data:
  #DB Secrets
  {{- if .Values.rdkitcatridgepostgres.enabled }}
  POSTGRES_PASSWORD: {{ required "A valid .Values.rdkitcatridgepostgres.auth.pgPassword entry required!" .Values.rdkitcatridgepostgres.auth.pgPassword |b64enc | quote }}
  {{- end -}}