apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdkitcatridgepostgres.fullname" . }}
  labels:
    {{- include "rdkitcatridgepostgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ include "rdkitcatridgepostgres.fullname" . }}
  selector:
    {{- include "rdkitcatridgepostgres.selectorLabels" . | nindent 4 }}

