{{- if eq (include "isProductionWithoutMasterKey" .) "true" }}
{{- $secretName := printf "%s-%s" (include "meilisearch.fullname" . ) "master-key" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ include "meilisearch.name" . }}
    helm.sh/chart: {{ include "meilisearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- if $secret }}
  MEILI_MASTER_KEY: {{ $secret.data.MEILI_MASTER_KEY }} 
  {{ else }}
  MEILI_MASTER_KEY: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{ end }}
