# Default values for coconut-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Default app properties for laravel.
appProperties:
  name: coconut
  key: 
  env: development
  debug: true
  url: https://coconut2.nmrxiv.org
  queueConnection: sync
  schemaVersion: 1.0
  description: |
    COCONUT Online is an open-source project that stores, searches, and analyzes Natural Products (NPs). 
    The database contains over 50 open NP resources, and the data is accessible free of charge and without any restrictions. 
    Each entry corresponds to a "flat" NP structure and is associated with their known stereochemical forms, 
    literature, organisms that produce them, natural geographic presence, and precomputed molecular properties if available.

webservices:
  europemcApi: https://www.ebi.ac.uk/europepmc/webservices/rest/search
  orcidIdSearchApi: https://pub.orcid.org/v2.1/search
  orcidIdEmploymentApi: https://pub.orcid.org/v3.0/{orcid_id}/employments
  orcidIdPersonApi: https://pub.orcid.org/v3.0/{orcid_id}/person
  cmApi: https://dev.api.naturalproducts.net/v1/


logProperties:
  logChannel: stack
  logLevel: debug

#DB Properties
rdkitcatridgepostgres:
  enabled: true
  auth:
    pgPassword: secret
    db: test
    user: test
    postgresPassword: secret
  connection: pgsql
  port: 5432

appImage:
  name: php
  repository: europe-west3-docker.pkg.dev/coconut-366808/coconut-dev/coconut-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nginxImage:
  name: nginx
  repository: europe-west3-docker.pkg.dev/coconut-366808/coconut-dev/coconut-nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

EnvConfigMapRef:
  name: "coconut-config-map"
  enabled: true
EnvSecretRef:
  name: "coconut-secrets"
  enabled: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {
  fsGroup: 82
}

securityContext: {
  runAsUser: 82,
  readOnlyRootFilesystem: true
}


service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {
    # kubernetes.io/ingress.global-static-ip-name: coconut-app-ip-address
    # kubernetes.io/ingress.class: "nginx"
  }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  app:
    limits:
      cpu: 400m
      memory: 250Mi
    requests:
      cpu: 250m
      memory: 125Mi
  nginx:
    limits:
      cpu: 400m
      memory: 250Mi
    requests:
      cpu: 250m
      memory: 125Mi

# Uncomment below properties and replace it with your own smtp values to activate the mail server.
mail:
  enabled: true
  host: 'smtp.uni-jena.de'
  port: 587
  from: info.coconut@uni-jena.de
  fromName: "coconut-dev"
  user: test
  password: secret
  mailer: smtp

cheminfo-microservice:
  enabled: false
  image:
    name: chem-py-microservice
    repository: europe-west3-docker.pkg.dev/coconut-366808/cheminformatics-python-microservice/chem-py-microservice
    pullPolicy: Always
    tag: latest
  service:
    type: ClusterIP
    port: 80

# oauthProperties:
#   enabled: false
#   twitterClientID: 
#   twitterClientSecret: 
#   twitterRedirectUrl: 
#   githubClientID: 
#   githubClientSecret: 
#   githubRedirectUrl: 
#   orcidClientID: 
#   orcidClientSecret:
#   orcidRedirectUrl:
#   orcidEnvironment:

#Enable this properties for Single Sign-On follow the documentation for more info https://docs.coconut.org/docs/developer-guides/configurations/oauth
# oauthProperties:
#   twitter:
#     enabled: false
#     clientID:
#     clientSecret:
#     redirectURL: 
#   github:
#     enabled: false
#     clientID:
#     clientSecret:
#     redirectURL:
#   orcid:
#     enabled: false
#     clientID:
#     clientSecret:
#     redirectURL:
#     environment:

# storage:
#   pvc:
#     accessModes:
#       - ReadWriteOnce
#     annotations: {}
#     enabled: true
#     existingClaim: ''
#     storage: 2Gi
#     # storageClassName: standard

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

worker:
  enabled: true
  replicaCount: 1
  autoscale:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    CPULimit: 70
    MemoryLimit: 1568Mi
  cmd: "php artisan horizon"
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 150Mi

redis:
  enabled: false
  #architecture: standalone
  auth:
    enabled: true
    password: secret
  global:
    storageClass: standard
  #host: nmrxiv-redis-master
  port: 6379
  replica:
    replicaCount: 1
  master:
    persistence:
      enabled: true
      size: 1Gi
    service:
      type: LoadBalancer
  replica:
    persistence:
      enabled: true
      size: 1Gi
  sessionDriver: redis
  cacheDriver: redis
  redisClient: predis
  sessionLifetime: 120
  memcachedHost: memcached

doi:
  doiHost: datacite
  doiProvider: datacite

scheduler:
  enabled: false
  replicaCount: 1
  autoscale:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    MemoryLimit: 1568Mi
  cmd: "php artisan schedule:work"
  resources:
    requests:
      cpu: 100m
      memory: 125Mi
    limits:
      cpu: 200m
      memory: 500Mi

larabug:
  enabled: false
  lbKey: 
  lbProjectKey:

fileStorage:
# Below values are for file storage configuration.
# You can have desired S3 compatible driver of your choice. Follow to read more https://laravel.com/docs/9.x/filesystem
  enabled: false
  fileSystemDriver: 
  fileSystemDriverPublic: 
  awsAccessKeyID: 
  awsSecretAccessKey: 
  awsDefaultRegion: 
  awsBucket: 
  awsEndpoint:
  awsURL: 

nodeSelector: {}

tolerations: []

affinity: {}
